using System.Configuration;

#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hey.Soardi.Model
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Carrozzeria2017")]
	public partial class CarrozzeriaDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertVeicoli_Note(Veicoli_Note instance);
    partial void UpdateVeicoli_Note(Veicoli_Note instance);
    partial void DeleteVeicoli_Note(Veicoli_Note instance);
    #endregion
		
		public CarrozzeriaDataContext() : 
				base(Connections.Carrozzeria, mappingSource)
		{
			OnCreated();
		}
		
		public CarrozzeriaDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CarrozzeriaDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CarrozzeriaDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CarrozzeriaDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Veicoli_Note> Veicoli_Notes
		{
			get
			{
				return this.GetTable<Veicoli_Note>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Veicoli_Note")]
	public partial class Veicoli_Note : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdNota;
		
		private int _IdVeicolo;
		
		private System.DateTime _DataNota;
		
		private string _Nota;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdNotaChanging(int value);
    partial void OnIdNotaChanged();
    partial void OnIdVeicoloChanging(int value);
    partial void OnIdVeicoloChanged();
    partial void OnDataNotaChanging(System.DateTime value);
    partial void OnDataNotaChanged();
    partial void OnNotaChanging(string value);
    partial void OnNotaChanged();
    #endregion
		
		public Veicoli_Note()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdNota", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdNota
		{
			get
			{
				return this._IdNota;
			}
			set
			{
				if ((this._IdNota != value))
				{
					this.OnIdNotaChanging(value);
					this.SendPropertyChanging();
					this._IdNota = value;
					this.SendPropertyChanged("IdNota");
					this.OnIdNotaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdVeicolo", DbType="Int NOT NULL")]
		public int IdVeicolo
		{
			get
			{
				return this._IdVeicolo;
			}
			set
			{
				if ((this._IdVeicolo != value))
				{
					this.OnIdVeicoloChanging(value);
					this.SendPropertyChanging();
					this._IdVeicolo = value;
					this.SendPropertyChanged("IdVeicolo");
					this.OnIdVeicoloChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DataNota", DbType="DateTime NOT NULL")]
		public System.DateTime DataNota
		{
			get
			{
				return this._DataNota;
			}
			set
			{
				if ((this._DataNota != value))
				{
					this.OnDataNotaChanging(value);
					this.SendPropertyChanging();
					this._DataNota = value;
					this.SendPropertyChanged("DataNota");
					this.OnDataNotaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nota", DbType="VarChar(500) NOT NULL", CanBeNull=false)]
		public string Nota
		{
			get
			{
				return this._Nota;
			}
			set
			{
				if ((this._Nota != value))
				{
					this.OnNotaChanging(value);
					this.SendPropertyChanging();
					this._Nota = value;
					this.SendPropertyChanged("Nota");
					this.OnNotaChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
